sudo: required
services:
  - postgresql
language: elixir
elixir:
  - 1.8.2
otp_release:
  - '21.3'
script:
  - mix test
  - "travis_wait 30 mix dialyzer --plt"
  - mix dialyzer --halt-exit-status
cache:
  - directories:
      - .dialyzer
